services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      checkit_net:
        ipv4_address: 172.16.3.5

  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:8080"
    networks:
      checkit_net:
        ipv4_address: 172.16.3.10

  db:
    image: couchdb:latest
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=${PASSWORD}
    ports:
      - "5984:5984"
    volumes:
      - ./couchdb-config/local.ini:/opt/couchdb/etc/local.d/cors.ini
    #  - couchdb_data:/opt/couchdb/data
    networks:
      checkit_net:
        ipv4_address: 172.16.3.20

networks:
  checkit_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.3.0/24
